name: interior_design
description: "A new Flutter project."


publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


#------------ Packages ----------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages

  # Icons
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8

  # State Management
  get: ^4.6.6
  http: ^1.1.2
  intl: ^0.19.0
  logger: ^2.0.2+1
  url_launcher: ^6.2.2
  get_storage: ^2.1.1
  carousel_slider: ^4.2.1
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0

  # Product Specific

  # Firebase
  firebase_core: ^3.1.1
  lottie: ^3.1.2
  connectivity_plus: ^5.0.2
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1
  google_nav_bar: ^5.0.6
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  firebase_storage: ^12.1.0
  cached_network_image: ^3.3.1

#------------ Packages End ----------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0


flutter:

  
  uses-material-design: true

#------------ Local Assets ----------#
  assets:
    - assets/icons/
    - assets/images/
    - assets/logos/
    - assets/animations/
    - assets/icons/
    - assets/images/banners/
    - assets/images/special/
    - assets/images/living_room/
    - assets/images/bed_room/
    - assets/images/bed_room/drawer/
    - assets/images/bed_room/wardrobe/
    - assets/images/living_room/sofa/
    - assets/images/living_room/tv_stand/
    - assets/images/bed_room/king_bed/
    - assets/images/living_room/coffee_table/
    - assets/images/kitchen/island_light/
    - assets/images/kitchen/sink/
    - assets/images/kitchen/faucet/
    - assets/images/kitchen/bin/
    - assets/images/dinning/
    - assets/images/kitchen/
    - assets/images/dinning/wine_rack/
    - assets/images/payment_methods/
    - assets/images/featured_products/
    - assets/images/dinning/
    - assets/images/on_boarding_images/

#------------ Local Fonts ----------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
    - family: Cookie
      fonts:
        - asset: assets/fonts/Cookie-Regular.ttf
          weight: 600
